// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ActionBarController from "./action_bar_controller"
application.register("action-bar", ActionBarController)

import BurgerController from "./burger_controller"
application.register("burger", BurgerController)

import ClearingController from "./clearing_controller"
application.register("clearing", ClearingController)

import PaybackController from "./payback_controller"
application.register("payback", PaybackController)
