services:
  web:
    build:
      context: ./
      dockerfile: development.Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bin/dev"
    volumes:
      - .:/usr/src/app
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - HISTFILE=/usr/src/app/log/.bash_history
      - REDIS_URL=redis://default:${REDIS_PASSWORD}@redis:6379/0
      - REDIS_TEST_URL=redis://default:${REDIS_PASSWORD}@redis_test:6379/0
    depends_on:
      db:
        condition: service_healthy
    networks:
      - external_network
      - internal_network
  db:
    image: postgres:17
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres
      interval: 2s
      timeout: 5s
      retries: 30
    networks:
      - internal_network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD} --protected-mode yes
    networks:
      - internal_network

  redis_test:
    image: redis:alpine
    ports:
      - "6380:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD} --protected-mode yes
    networks:
      - internal_network

networks:
  external_network:
  internal_network:
    internal: true

volumes:
  pg_data:
  bundle:
  redis_data:
